version: "3"
services:
  restaurant-local:
    image: postgres
    restart: always
    container_name: restaurant-local
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "restaurant"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15433:5432"
